name: Upload GitHub LFS Data to Azure Storage

on:
  workflow_dispatch:  # You can manually run this anytime

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with Git LFS
        uses: actions/checkout@v3
        with:
          lfs: true  # Required to pull actual data files

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Upload to Azure Blob Storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          az storage blob upload-batch \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            --account-key "$AZURE_STORAGE_KEY" \
            --destination 'data/bronze' \
            --source './Data' \
            --pattern '*'
          